version: '3'

services:
  mysql:
    container_name: DB
    image: mysql:5.7.28
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=invitao
      - MYSQL_PASSWORD=secret123
    # volumes:
    #     - db-sql:/var/lib/mysql

  phpmyadmin:
    container_name: DBMS
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  # scraper:
  #   container_name: db_scrapper
  #   build: 
  #     context: ../
  #     dockerfile: ./contenedor_tres/Dockerfile
  #   depends_on:
  #     - mysql
# volumes:
#     db-sql: