version: "3"

services:
  mysql:
    container_name: DATABASE
    image: mysql:5.7.28
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=invitao
      - MYSQL_PASSWORD=secret123
    #healthcheck:
    # acá están algunos de los que he probado
    #test: mysql ping -h 127.0.0.1:3306 -u $$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD
    #test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    #test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
    #test: ["CMD", "mysqladmin", "ping", "-proot", "-h", "localhost"]
    #test: '/usr/bin/mysql --user=root --password=root --execute "SHOW DATABASES;"'
    # test: [
    #     "CMD",
    #     "mysqladmin",
    #     "ping",
    #     # "-h",
    #     "0.0.0.0:3306",
    #     "mysql",
    #     "-uroot",
    #     "-proot",
    #   ]
    # interval: 10s
    # timeout: 10s
    # retries: 5

    # volumes:
    #     - db-sql:/var/lib/mysql

  phpmyadmin:
    container_name: DBMS
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  scraper:
    container_name: scrapper
    build:
      context: ./contenedor-tres/.
      dockerfile: Dockerfile
    #restart: on-failure
    depends_on:
      - mysql
        #condition: service_healthy
# volumes:
#     db-sql:
