version: "3"

services:
  mysql:
    container_name: DATABASE
    image: mysql:5.7.28
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=invitao
      - MYSQL_PASSWORD=secret123
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    # volumes:
    #     - db-sql:/var/lib/mysql

  phpmyadmin:
    container_name: DBMS
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  scraper:
    container_name: scrapper
    build:
      context: ./contenedor-tres/.
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      mysql:
            condition: service_healthy

# volumes:
#     db-sql:
